version: '3'
services:
  token-distribution-service:
    container_name: token-distribution-service
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_DIR=logs
    links:
      - redis
  token-distribution-service2:
    container_name: token-distribution-service2
    build: .
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_DIR=logs
    links:
      - redis
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6389:6379"